//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggingCodefirst.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BrandResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BrandResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LoggingCodefirst.Resources.BrandResource", typeof(BrandResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string msg_CreateBrandSuccess {
            get {
                return ResourceManager.GetString("msg_CreateBrandSuccess", resourceCulture);
            }
        }
        
        public static string err_CreateBrand {
            get {
                return ResourceManager.GetString("err_CreateBrand", resourceCulture);
            }
        }
        
        public static string msg_EditBrandSuccess {
            get {
                return ResourceManager.GetString("msg_EditBrandSuccess", resourceCulture);
            }
        }
        
        public static string err_EditBrand {
            get {
                return ResourceManager.GetString("err_EditBrand", resourceCulture);
            }
        }
        
        public static string msg_DeleteBrandSuccess {
            get {
                return ResourceManager.GetString("msg_DeleteBrandSuccess", resourceCulture);
            }
        }
        
        public static string err_DeleteBrand {
            get {
                return ResourceManager.GetString("err_DeleteBrand", resourceCulture);
            }
        }
        
        public static string msg_DeleteBrand {
            get {
                return ResourceManager.GetString("msg_DeleteBrand", resourceCulture);
            }
        }
        
        public static string lbl_Brand {
            get {
                return ResourceManager.GetString("lbl_Brand", resourceCulture);
            }
        }
        
        public static string lbl_CreateBrand {
            get {
                return ResourceManager.GetString("lbl_CreateBrand", resourceCulture);
            }
        }
        
        public static string lbl_EditBrand {
            get {
                return ResourceManager.GetString("lbl_EditBrand", resourceCulture);
            }
        }
        
        public static string lbl_No {
            get {
                return ResourceManager.GetString("lbl_No", resourceCulture);
            }
        }
        
        public static string lbl_BrandName {
            get {
                return ResourceManager.GetString("lbl_BrandName", resourceCulture);
            }
        }
        
        public static string lbl_Action {
            get {
                return ResourceManager.GetString("lbl_Action", resourceCulture);
            }
        }
        
        public static string msg_NotEmpty {
            get {
                return ResourceManager.GetString("msg_NotEmpty", resourceCulture);
            }
        }
        
        public static string msg_Exists {
            get {
                return ResourceManager.GetString("msg_Exists", resourceCulture);
            }
        }
    }
}
