//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggingCodefirst.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LoggingCodefirst.Resources.CategoryResource", typeof(CategoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string msg_CreateCategorySuccess {
            get {
                return ResourceManager.GetString("msg_CreateCategorySuccess", resourceCulture);
            }
        }
        
        public static string err_CreateCategory {
            get {
                return ResourceManager.GetString("err_CreateCategory", resourceCulture);
            }
        }
        
        public static string msg_EditCategorySuccess {
            get {
                return ResourceManager.GetString("msg_EditCategorySuccess", resourceCulture);
            }
        }
        
        public static string err_EditCategory {
            get {
                return ResourceManager.GetString("err_EditCategory", resourceCulture);
            }
        }
        
        public static string msg_DeleteCategorySuccess {
            get {
                return ResourceManager.GetString("msg_DeleteCategorySuccess", resourceCulture);
            }
        }
        
        public static string err_DeleteCategory {
            get {
                return ResourceManager.GetString("err_DeleteCategory", resourceCulture);
            }
        }
        
        public static string msg_DeleteCategory {
            get {
                return ResourceManager.GetString("msg_DeleteCategory", resourceCulture);
            }
        }
        
        public static string lbl_Category {
            get {
                return ResourceManager.GetString("lbl_Category", resourceCulture);
            }
        }
        
        public static string lbl_CreateCategory {
            get {
                return ResourceManager.GetString("lbl_CreateCategory", resourceCulture);
            }
        }
        
        public static string lbl_EditCategory {
            get {
                return ResourceManager.GetString("lbl_EditCategory", resourceCulture);
            }
        }
        
        public static string lbl_No {
            get {
                return ResourceManager.GetString("lbl_No", resourceCulture);
            }
        }
        
        public static string lbl_CategoryName {
            get {
                return ResourceManager.GetString("lbl_CategoryName", resourceCulture);
            }
        }
        
        public static string lbl_Action {
            get {
                return ResourceManager.GetString("lbl_Action", resourceCulture);
            }
        }
        
        public static string msg_NotEmpty {
            get {
                return ResourceManager.GetString("msg_NotEmpty", resourceCulture);
            }
        }
        
        public static string msg_Exists {
            get {
                return ResourceManager.GetString("msg_Exists", resourceCulture);
            }
        }
    }
}
