//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggingCodefirst.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LoggingCodefirst.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string btn_Back {
            get {
                return ResourceManager.GetString("btn_Back", resourceCulture);
            }
        }
        
        public static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        public static string btn_Create {
            get {
                return ResourceManager.GetString("btn_Create", resourceCulture);
            }
        }
        
        public static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        public static string btn_ForgotPassword {
            get {
                return ResourceManager.GetString("btn_ForgotPassword", resourceCulture);
            }
        }
        
        public static string msg_ForgotPassword {
            get {
                return ResourceManager.GetString("msg_ForgotPassword", resourceCulture);
            }
        }
        
        public static string lbl_EmailAddress {
            get {
                return ResourceManager.GetString("lbl_EmailAddress", resourceCulture);
            }
        }
        
        public static string lbl_Password {
            get {
                return ResourceManager.GetString("lbl_Password", resourceCulture);
            }
        }
        
        public static string btn_Recover {
            get {
                return ResourceManager.GetString("btn_Recover", resourceCulture);
            }
        }
        
        public static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        public static string lbl_Hello {
            get {
                return ResourceManager.GetString("lbl_Hello", resourceCulture);
            }
        }
        
        public static string btn_AccountSetting {
            get {
                return ResourceManager.GetString("btn_AccountSetting", resourceCulture);
            }
        }
        
        public static string btn_ChangePassword {
            get {
                return ResourceManager.GetString("btn_ChangePassword", resourceCulture);
            }
        }
        
        public static string btn_Logout {
            get {
                return ResourceManager.GetString("btn_Logout", resourceCulture);
            }
        }
        
        public static string btn_Index {
            get {
                return ResourceManager.GetString("btn_Index", resourceCulture);
            }
        }
        
        public static string btn_Home {
            get {
                return ResourceManager.GetString("btn_Home", resourceCulture);
            }
        }
        
        public static string btn_Privacy {
            get {
                return ResourceManager.GetString("btn_Privacy", resourceCulture);
            }
        }
        
        public static string btn_User {
            get {
                return ResourceManager.GetString("btn_User", resourceCulture);
            }
        }
        
        public static string btn_Store {
            get {
                return ResourceManager.GetString("btn_Store", resourceCulture);
            }
        }
        
        public static string btn_Brand {
            get {
                return ResourceManager.GetString("btn_Brand", resourceCulture);
            }
        }
        
        public static string btn_Category {
            get {
                return ResourceManager.GetString("btn_Category", resourceCulture);
            }
        }
        
        public static string btn_Product {
            get {
                return ResourceManager.GetString("btn_Product", resourceCulture);
            }
        }
        
        public static string btn_Stock {
            get {
                return ResourceManager.GetString("btn_Stock", resourceCulture);
            }
        }
        
        public static string btn_Language {
            get {
                return ResourceManager.GetString("btn_Language", resourceCulture);
            }
        }
        
        public static string msg_Success {
            get {
                return ResourceManager.GetString("msg_Success", resourceCulture);
            }
        }
        
        public static string msg_Error {
            get {
                return ResourceManager.GetString("msg_Error", resourceCulture);
            }
        }
    }
}
