//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggingCodefirst.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LoggingCodefirst.Resources.ProductResource", typeof(ProductResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string msg_CreateProductSuccess {
            get {
                return ResourceManager.GetString("msg_CreateProductSuccess", resourceCulture);
            }
        }
        
        public static string err_CreateProduct {
            get {
                return ResourceManager.GetString("err_CreateProduct", resourceCulture);
            }
        }
        
        public static string msg_EditProductSuccess {
            get {
                return ResourceManager.GetString("msg_EditProductSuccess", resourceCulture);
            }
        }
        
        public static string err_EditProduct {
            get {
                return ResourceManager.GetString("err_EditProduct", resourceCulture);
            }
        }
        
        public static string msg_DeleteProductSuccess {
            get {
                return ResourceManager.GetString("msg_DeleteProductSuccess", resourceCulture);
            }
        }
        
        public static string err_DeleteProduct {
            get {
                return ResourceManager.GetString("err_DeleteProduct", resourceCulture);
            }
        }
        
        public static string msg_DeleteProduct {
            get {
                return ResourceManager.GetString("msg_DeleteProduct", resourceCulture);
            }
        }
        
        public static string lbl_Product {
            get {
                return ResourceManager.GetString("lbl_Product", resourceCulture);
            }
        }
        
        public static string lbl_CreateProduct {
            get {
                return ResourceManager.GetString("lbl_CreateProduct", resourceCulture);
            }
        }
        
        public static string lbl_EditProduct {
            get {
                return ResourceManager.GetString("lbl_EditProduct", resourceCulture);
            }
        }
        
        public static string lbl_No {
            get {
                return ResourceManager.GetString("lbl_No", resourceCulture);
            }
        }
        
        public static string lbl_ProductName {
            get {
                return ResourceManager.GetString("lbl_ProductName", resourceCulture);
            }
        }
        
        public static string lbl_Brand {
            get {
                return ResourceManager.GetString("lbl_Brand", resourceCulture);
            }
        }
        
        public static string lbl_Category {
            get {
                return ResourceManager.GetString("lbl_Category", resourceCulture);
            }
        }
        
        public static string lbl_ModelYear {
            get {
                return ResourceManager.GetString("lbl_ModelYear", resourceCulture);
            }
        }
        
        public static string lbl_ListPrice {
            get {
                return ResourceManager.GetString("lbl_ListPrice", resourceCulture);
            }
        }
        
        public static string lbl_Stocks {
            get {
                return ResourceManager.GetString("lbl_Stocks", resourceCulture);
            }
        }
        
        public static string lbl_ProductImage {
            get {
                return ResourceManager.GetString("lbl_ProductImage", resourceCulture);
            }
        }
        
        public static string lbl_Action {
            get {
                return ResourceManager.GetString("lbl_Action", resourceCulture);
            }
        }
        
        public static string msg_ProductNameNotEmpty {
            get {
                return ResourceManager.GetString("msg_ProductNameNotEmpty", resourceCulture);
            }
        }
        
        public static string msg_ListPriceNotEmpty {
            get {
                return ResourceManager.GetString("msg_ListPriceNotEmpty", resourceCulture);
            }
        }
        
        public static string msg_ImageFileNotEmpty {
            get {
                return ResourceManager.GetString("msg_ImageFileNotEmpty", resourceCulture);
            }
        }
        
        public static string msg_ModelYearNotEmpty {
            get {
                return ResourceManager.GetString("msg_ModelYearNotEmpty", resourceCulture);
            }
        }
    }
}
