//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggingCodefirst.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StockResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StockResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LoggingCodefirst.Resources.StockResource", typeof(StockResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string msg_CreateStockSuccess {
            get {
                return ResourceManager.GetString("msg_CreateStockSuccess", resourceCulture);
            }
        }
        
        public static string err_CreateStock {
            get {
                return ResourceManager.GetString("err_CreateStock", resourceCulture);
            }
        }
        
        public static string msg_EditStockSuccess {
            get {
                return ResourceManager.GetString("msg_EditStockSuccess", resourceCulture);
            }
        }
        
        public static string err_EditStock {
            get {
                return ResourceManager.GetString("err_EditStock", resourceCulture);
            }
        }
        
        public static string msg_DeleteStockSuccess {
            get {
                return ResourceManager.GetString("msg_DeleteStockSuccess", resourceCulture);
            }
        }
        
        public static string err_DeleteStock {
            get {
                return ResourceManager.GetString("err_DeleteStock", resourceCulture);
            }
        }
        
        public static string msg_DeleteStock {
            get {
                return ResourceManager.GetString("msg_DeleteStock", resourceCulture);
            }
        }
        
        public static string lbl_Stock {
            get {
                return ResourceManager.GetString("lbl_Stock", resourceCulture);
            }
        }
        
        public static string lbl_CreateStock {
            get {
                return ResourceManager.GetString("lbl_CreateStock", resourceCulture);
            }
        }
        
        public static string lbl_EditStock {
            get {
                return ResourceManager.GetString("lbl_EditStock", resourceCulture);
            }
        }
        
        public static string lbl_No {
            get {
                return ResourceManager.GetString("lbl_No", resourceCulture);
            }
        }
        
        public static string lbl_Store {
            get {
                return ResourceManager.GetString("lbl_Store", resourceCulture);
            }
        }
        
        public static string lbl_Product {
            get {
                return ResourceManager.GetString("lbl_Product", resourceCulture);
            }
        }
        
        public static string lbl_Quantity {
            get {
                return ResourceManager.GetString("lbl_Quantity", resourceCulture);
            }
        }
        
        public static string lbl_Action {
            get {
                return ResourceManager.GetString("lbl_Action", resourceCulture);
            }
        }
        
        public static string msg_GreaterThanOrEqualTo1 {
            get {
                return ResourceManager.GetString("msg_GreaterThanOrEqualTo1", resourceCulture);
            }
        }
    }
}
