//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggingCodefirst.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoreResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LoggingCodefirst.Resources.StoreResource", typeof(StoreResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string msg_CreateStoreSuccess {
            get {
                return ResourceManager.GetString("msg_CreateStoreSuccess", resourceCulture);
            }
        }
        
        public static string err_CreateStore {
            get {
                return ResourceManager.GetString("err_CreateStore", resourceCulture);
            }
        }
        
        public static string msg_EditStoreSuccess {
            get {
                return ResourceManager.GetString("msg_EditStoreSuccess", resourceCulture);
            }
        }
        
        public static string err_EditStore {
            get {
                return ResourceManager.GetString("err_EditStore", resourceCulture);
            }
        }
        
        public static string msg_DeleteStoreSuccess {
            get {
                return ResourceManager.GetString("msg_DeleteStoreSuccess", resourceCulture);
            }
        }
        
        public static string err_DeleteStore {
            get {
                return ResourceManager.GetString("err_DeleteStore", resourceCulture);
            }
        }
        
        public static string msg_DeleteStore {
            get {
                return ResourceManager.GetString("msg_DeleteStore", resourceCulture);
            }
        }
        
        public static string lbl_Store {
            get {
                return ResourceManager.GetString("lbl_Store", resourceCulture);
            }
        }
        
        public static string lbl_CreateStore {
            get {
                return ResourceManager.GetString("lbl_CreateStore", resourceCulture);
            }
        }
        
        public static string lbl_EditStore {
            get {
                return ResourceManager.GetString("lbl_EditStore", resourceCulture);
            }
        }
        
        public static string lbl_No {
            get {
                return ResourceManager.GetString("lbl_No", resourceCulture);
            }
        }
        
        public static string lbl_StoreName {
            get {
                return ResourceManager.GetString("lbl_StoreName", resourceCulture);
            }
        }
        
        public static string lbl_Email {
            get {
                return ResourceManager.GetString("lbl_Email", resourceCulture);
            }
        }
        
        public static string lbl_Phone {
            get {
                return ResourceManager.GetString("lbl_Phone", resourceCulture);
            }
        }
        
        public static string lbl_Address {
            get {
                return ResourceManager.GetString("lbl_Address", resourceCulture);
            }
        }
        
        public static string lbl_State {
            get {
                return ResourceManager.GetString("lbl_State", resourceCulture);
            }
        }
        
        public static string lbl_City {
            get {
                return ResourceManager.GetString("lbl_City", resourceCulture);
            }
        }
        
        public static string lbl_Street {
            get {
                return ResourceManager.GetString("lbl_Street", resourceCulture);
            }
        }
        
        public static string lbl_Stocks {
            get {
                return ResourceManager.GetString("lbl_Stocks", resourceCulture);
            }
        }
        
        public static string lbl_ZipCode {
            get {
                return ResourceManager.GetString("lbl_ZipCode", resourceCulture);
            }
        }
        
        public static string lbl_Action {
            get {
                return ResourceManager.GetString("lbl_Action", resourceCulture);
            }
        }
    }
}
