//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggingCodefirst.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LoggingCodefirst.Resources.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_400Detail {
            get {
                return ResourceManager.GetString("lbl_400Detail", resourceCulture);
            }
        }
        
        public static string lbl_400Title {
            get {
                return ResourceManager.GetString("lbl_400Title", resourceCulture);
            }
        }
        
        public static string lbl_401Detail {
            get {
                return ResourceManager.GetString("lbl_401Detail", resourceCulture);
            }
        }
        
        public static string lbl_401Title {
            get {
                return ResourceManager.GetString("lbl_401Title", resourceCulture);
            }
        }
        
        public static string lbl_403Detail {
            get {
                return ResourceManager.GetString("lbl_403Detail", resourceCulture);
            }
        }
        
        public static string lbl_403Title {
            get {
                return ResourceManager.GetString("lbl_403Title", resourceCulture);
            }
        }
        
        public static string lbl_404Detail {
            get {
                return ResourceManager.GetString("lbl_404Detail", resourceCulture);
            }
        }
        
        public static string lbl_404Title {
            get {
                return ResourceManager.GetString("lbl_404Title", resourceCulture);
            }
        }
        
        public static string lbl_405Detail {
            get {
                return ResourceManager.GetString("lbl_405Detail", resourceCulture);
            }
        }
        
        public static string lbl_405Title {
            get {
                return ResourceManager.GetString("lbl_405Title", resourceCulture);
            }
        }
        
        public static string lbl_500Detail {
            get {
                return ResourceManager.GetString("lbl_500Detail", resourceCulture);
            }
        }
        
        public static string lbl_500Title {
            get {
                return ResourceManager.GetString("lbl_500Title", resourceCulture);
            }
        }
    }
}
