//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggingCodefirst.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LoggingCodefirst.Resources.HomeResource", typeof(HomeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_Index {
            get {
                return ResourceManager.GetString("lbl_Index", resourceCulture);
            }
        }
        
        public static string lbl_Privacy {
            get {
                return ResourceManager.GetString("lbl_Privacy", resourceCulture);
            }
        }
        
        public static string lbl_Welcome {
            get {
                return ResourceManager.GetString("lbl_Welcome", resourceCulture);
            }
        }
        
        public static string lbl_IndexDetail1 {
            get {
                return ResourceManager.GetString("lbl_IndexDetail1", resourceCulture);
            }
        }
        
        public static string lbl_IndexDetail2 {
            get {
                return ResourceManager.GetString("lbl_IndexDetail2", resourceCulture);
            }
        }
        
        public static string lbl_PrivacyDetail {
            get {
                return ResourceManager.GetString("lbl_PrivacyDetail", resourceCulture);
            }
        }
    }
}
